### ISSUE TITLE
Install from docker compose?

### ISSUE THREAD

**Issue by Failead0r** [raujimenez/tiktok-discord-bot#1]
Good afternoon, I tried to install your bot through docker compose but no luck with this:

```
version: '3'

services:

  tiktok:
    image: raujimenez/tiktok-downloader-discord-bot:latest
    container_name: TikTokDownloaderBot
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NODE_VERSION=12.22.1
      - YARN_VERSION=1.22.5
      - TOKEN=token_bot
    ports:
      - 10080:80
      - 18080:8080
    restart: unless-stopped
```

Can you help me, please?
